### ISSUE TITLE
Haskell highlighting

### ISSUE THREAD

**Issue by willdoescode** [mausworks/mausworks-theme-vscode#10]
Keywords and typenames should probably pop out more.

![Screen Shot 2021-05-21 at 14 31 18](https://user-images.githubusercontent.com/53620720/119200153-359c2c00-ba41-11eb-9b6c-19a488dc2b5e.png)

**Comment by willdoescode** [comment]
The pipe operators should also be a different color something more bright to really stand out.

![Screen Shot 2021-05-21 at 14 32 57](https://user-images.githubusercontent.com/53620720/119200263-709e5f80-ba41-11eb-8719-6abc156aab6c.png)

**Comment by willdoescode** [comment]
For reference this is from the theme I currently use.

![Screen Shot 2021-05-21 at 14 37 18](https://user-images.githubusercontent.com/53620720/119200571-0c2fd000-ba42-11eb-9d72-c799a66665b6.png)

**Comment by willdoescode** [comment]
I think the pipe operator could be the same sort of keyword color as the pink color.

**Comment by mausworks** [comment]
@willdoescode I did what could be done in #12 :+1:
