### ISSUE TITLE
Rust keyword highlighting

### ISSUE THREAD

**Issue by wijiler** [mausworks/mausworks-theme-vscode#11]
I was creating a web server with actix when I noticed that things like async and use are grey and don't pop out as I think they should also .await and fn are  grey too

**Comment by mausworks** [comment]
Thank you very much for this issue! I certainly think that `.await` should pop out (it's a function, right)?

As for `fn`, this is a keyword, and in this theme keywords are toned down.

Could you provide me with a code example that I can test against? :)

**Comment by mausworks** [comment]
Actually, I cloned some random Actix project and had a look. I think it looks "as intended". 

Like I previously said, `await` is a keyword, and so is `fn`, `async`, `use` etc. 

The Night theme intentionally tones these down, as I don't consider keywords to be "first class information" (that would be function names, class/struct names, module names and data).

However, it is unfortunate that Rust puts the `await` keyword _after_ the function call (unlike most other languages).
I have highlighted some rust keywords (`mut` is one of them) and maybe I should do the same for await.

Please let me know how you want me to improve this.

**Comment by mausworks** [comment]
I looked into it. There's no way to specifically target the `await` keyword in rust.

The scope for it is: `keyword.control.rust`, which means it will have to stay the way it is.

I hope this theme can bring you joy regardless :heart:
